### ISSUE TITLE
Exception in periodic task for alarm update

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#133]
Screen grab from operator's workstation. Looking at CloudWatch Logs stream for alarm updater task. Some alarm records weren't updating in DynamoDB and this exception was encountered repeatedly.

![image](https://user-images.githubusercontent.com/33331284/80029594-d9f91b00-849b-11ea-8260-23943d43913f.png)

**Comment by JimTharioAmazon** [comment]
This may be related to Alarms deleted in the console and we're not handling that gracefully.

**Comment by JimTharioAmazon** [comment]
Recreated:

```
'NoneType' object has no attribute 'get': AttributeError
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1430, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 324, in update_alarms
    return periodic_handlers.update_alarms()
  File "/var/task/chalicelib/periodic.py", line 61, in update_alarms
    "StateValue": alarm.state_value,
  File "/var/task/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by JimTharioAmazon** [comment]
We also needed to clear the function memoize cache on the front-end when alarms change state. This allows the UI controls to retrieve the updated alarm details from the API.

**Comment by JimTharioAmazon** [comment]
Reopening for fix on the subscribe dialog to make sure it shows current alarm status.

**Comment by JimTharioAmazon** [comment]
Alarm subscribe and unsubscribe need to clear the cache of a single ARN only, not the entire cache.
